apiVersion: v1
kind: Service
metadata:
  name: loki-stack-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: loki
    release: loki-stack
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100 #
