apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-stack-cert
  namespace: monitoring
spec:
  secretName: prometheus-stack-tls-secret
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - alertmanager.patron.boss
    - grafana.patron.boss
    - prometheus.patron.boss