---

- name: update apt packages
  apt:
    update_cache: yes
    upgrade: dist
  ignore_errors: yes
  tags: essential
  when:
    - ansible_os_family == "Debian"
    - ansible_date_time.hour|int >= 1
    - ansible_date_time.hour|int <= 8

- name: update yum packages
  yum:
    name: "*"
    state: latest
  ignore_errors: yes
  tags: essential
  when:
    - ansible_os_family == "Redhat"
    - ansible_date_time.hour|int >= 1
    - ansible_date_time.hour|int <= 8

- name: install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present
  ignore_errors: yes
  tags: essential
  when:
    - ansible_date_time.hour|int >= 1
    - ansible_date_time.hour|int <= 8

- name: set hostname
  hostname:
    name: "{{ host_hostname }}"
  when: 
    - taggies is not search("dns") 
    - taggies is not search("k3s")
  tags: essential

- name: replace hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 localhost {{ host_hostname }}"
    owner: root
    group: root
    mode: "0644"
  when: 
    - taggies is not search("dns") 
    - taggies is not search("k3s")
  tags: essential