- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: docker

- name: Upgrade all apt packages
  apt: upgrade=dist
  tags: docker

- name: Install dependencies
  apt:
    name: "{{ docker_deps }}"
    state: present
    update_cache: yes
  tags: docker
      
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_release }} stable
    state: present
  tags: docker

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  tags: docker
    

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker
  tags: docker

- name: Install python packages
  pip:
    name: docker
  tags: docker