- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: docker

- name: Upgrade all apt packages
  apt: upgrade=dist
  tags: docker

- name: Install dependencies
  apt:
    name: "{{ docker_deps }}"
    state: present
    update_cache: yes
  tags: docker
      
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_release }} stable
    state: present
  tags: docker

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  tags: docker
    

- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker
  tags: docker

- name: Install python packages
  pip:
    name: docker
  tags: docker

- name: Create uptime kuma container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:latest
    state: started
    recreate: false
    restart_policy: always
    published_ports:
      - "3001:3001"
    volumes:
      - /docker-data/uptime-kuma/data:/app/data 
  tags: docker, uptime_kuma

- name: Create postgres container
  docker_container:
    name: postgres
    image: postgres
    state: started
    recreate: false
    restart_policy: always
    published_ports:
      - "5432:5432"
    volumes:
      - /docker-data/postgres/data:/var/lib/postgresql/data
    env:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password}}"

  tags: docker, postgres