---
- name: Install GitHub Actions Runner
  hosts: all
  user: ubuntu
  become: yes
  vars:
    - github_account: vcaster
    - github_repo: Homelab
  roles:
    - role: monolithprojects.github_actions_runner
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - nodejs
          - python3
          - python3-pip
          - pass
        state: present
    - name: Install pip modules
      pip:
        name: 
          - ansible
          - netaddr
        state: latest
    - name: Copy requirements.yml
      become_user: ubuntu
      copy:
        src: ../k3s-ansible/collections/requirements.yml
        dest: /tmp
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Install k3s requirements
      become_user: ubuntu
      shell:
        cmd: ansible-galaxy collection install -r ./requirements.yml
        chdir: /tmp
    - name: Creating a symlink for node
      file:
        src: "/usr/bin/nodejs"
        dest: "/usr/local/bin/node"
        state: link
    - name: Copy private keys
      copy:
        src: ../../../Forbidden-Fruit/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    - name: Copy public keys
      copy:
        src: ../../../Forbidden-Fruit/id_rsa.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Copy pgp keys
      copy:
        src: ../../../Forbidden-Fruit/private.gpg.key
        dest: /home/ubuntu/.ssh/private.gpg.key
        owner: ubuntu
        group: ubuntu
        mode: '0600'
    - name: Import a key from a file
      become_user: ubuntu
      shell:
        cmd: gpg --import private.gpg.key
        chdir: /home/ubuntu/.ssh/
    - name: Clone a github repository
      become_user: ubuntu
      git:
        repo: git@github.com:vcaster/Forbidden-Fruit.git
        dest: /home/ubuntu/Forbidden-Fruit
        accept_hostkey: yes
        clone: yes
        update: yes
      
