---
- name: Install GitHub Actions Runner
  hosts: all
  user: ubuntu
  become: yes
  vars:
    - github_account: vcaster
    - github_repo: Homelab
  roles:
    - role: monolithprojects.github_actions_runner
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - nodejs
          - python3
          - python3-pip
        state: present
    - name: Install Ansible
      pip:
        name: ansible
        state: latest
    - name: Creating a symlink for node
      file:
        src: "/usr/bin/nodejs"
        dest: "/usr/local/bin/node"
        state: link
      
