---

- name: configure linux
  hosts: linux
  become: yes
  tasks:

  roles:
    - role: system
    - role: zabbix-linux
    - role: node-exporter
    - role: promtail

- name: configure docker
  hosts: docker
  become: yes
  tasks:

  roles:
    - role: docker
    - role: syncthing

- name: configure pihole
  hosts: pihole
  become: yes
  tasks:

  roles:
    - role: pihole