apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: authelia-config
  namespace: authelia
data:
  configuration.yml: |-
    ###############################################################
    #                   Authelia configuration                    #
    ###############################################################

    # The host and port to listen on
    server:
      host: 0.0.0.0
      port: 9091

    theme: dark

    # Level of verbosity for logs: info, debug, trace
    log_level: debug

    log_file_path: /var/log/authelia

    # jwt_secret: Nope

    # Default redirection URL

    default_redirection_url: https://heimdall.patron.boss/

    totp:
      issuer: authelia.com
      period: 30
      skew: 1
    
    # webauthn:
    #   disable: false
    #   display_name: Authelia
    #   attestation_conveyance_preference: indirect
    #   user_verification: preferred
    #   timeout: 60s

    authentication_backend:
      # Disable both the HTML element and the API for reset password functionality
      disable_reset_password: false
      file:
        path: /config/users.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          memory: 1024
          parallelism: 8

    access_control:
      # Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'.
      # It is the policy applied to any resource if there is no policy to be applied
      # to the user.
      default_policy: deny

      rules:
        # Rules applied to everyone
        - domain: longhorn.patron.boss
          policy: two_factor
          networks:
            - 10.10.0.0/16

        - domain: heimdall.patron.boss
          policy: bypass

        - domain: public-real.patron.boss
          policy: one_factor
          networks:
            - 10.10.0.0/16
        - domain: admin-real.patron.boss
          policy: two_factor

    session:
      # The name of the session cookie. (default: authelia_session).
      name: authelia_session
      #secret: Nope
      expiration: 1h
      inactivity: 5m

      remember_me_duration: 1M

      domain: patron.boss

      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
        # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD
        # password: Nope
        # This is the Redis DB Index https://redis.io/commands/select (sometimes referred to as database number, DB, etc).
        database_index: 0

    regulation:
      max_retries: 3

      find_time: 2m

      ban_time: 5m

    storage:
      encryption_key: a_very_important_secret
      postgres:
        host: 10.10.50.1
        port: 5434
        database: authelia
        username: authelia
        # This secret can also be set using the env variables AUTHELIA_STORAGE_POSTGRES_PASSWORD
        # password: Nope
      # The directory where the DB files will be saved
      # local:
      #   path: /config/db.sqlite3

    notifier:
      # For testing purpose, notifications can be sent in a file
      # filesystem:
      #   filename: /tmp/authelia/notification.txt

      smtp:
        username: AKIARIB4XRH4NMG5HRV4
        # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD
        #password: Nope
        host: email-smtp.us-east-1.amazonaws.com
        port: 465
        sender: authelia@patroner.org
        # Subject configuration of the emails sent.
        # {title} is replaced by the text from the notifier
        subject: "[Authelia] {title}"

  users.yaml: |-
    users:
      zeke:
        disabled: false
        displayname: "Authelia User"
        # Password is authelia
        password: "$argon2id$v=19$m=65536,t=3,p=4$L5GrUbT7QUns1mpX12Br+g$R5jDjpzcTJyfIvrQjDoAkbhr3nlUlICE+TKMbq2FRrk"  # yamllint disable-line rule:line-length
        email: ezekielaina20@yahoo.com
        groups:
          - admins
          - dev


