---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:4.37.5
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: config-volume-conf
          mountPath: /config
          readOnly: false     
      volumes:
      - name: config-volume-conf
        configMap:
          defaultMode: 0777
          name: authelia-config
          items:
          - key: configuration.yml
            path: configuration.yml 
          - key: users.yaml
            path: users.yaml 

---
apiVersion: v1
kind: Service
metadata:
  name: authelia-service
  namespace: authelia
spec:
  selector:
    app: authelia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # using cert manager CRD to generate cert
spec:
  tls:
  - secretName: authelia-ingress-tls
    hosts:
    - authelia.patron.boss # This is the host to reach Authelia login page
  rules:
  - host: authelia.patron.boss # This is the host to reach Authelia login page
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
                name: authelia-service
                port:
                  number: 80