server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.90.86:3100/loki/api/v1/push

scrape_configs:
- job_name: local_{{ host_name }}
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs_{{ host_name }}
      __path__: /var/log/*/*log
