apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-tls-secret
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.patron.boss