apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zabbix-cert
  namespace: zabbix
spec:
  secretName: zabbix-tls-secret
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - zabbix.patron.boss