apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
  namespace: authelia

spec:
  storageClassName: "longhorn" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  