 name: Deploy Packer Locally
 
on:
  push:
    branches:
      - main
    paths:
    - Packer
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip packer_1.7.4_linux_amd64.zip
        sudo mv packer /usr/local/bin
 
    - name: Build Packer Image
      run: |
        packer build -on-error=ask -var-file Packer/variables.pkrvars100GBdisk.hcl -var-file Packer/vsphere.pkrvars.hcl Packer/ubuntu-22.04.pkr.hcl